//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Order_id { get; set; }
        public System.DateTime Booking_date { get; set; }
        public System.DateTime Return_date { get; set; }
        public string Description { get; set; }
        public int Car_id { get; set; }
        public string User_id { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
